### ISSUE TITLE
Tensorflow requirements conflict

### ISSUE THREAD

**Issue by gmmarconi** [NoemieJaquier/GaBOflow#1]
I am trying to install the repo, when installing GPflow (https://github.com/GPflow/GPflowOpt), I get the following error:

`ERROR: tensorflow 2.1.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.2.1 which is incompatible.`

However it is required by pymanopt to have scipy <= 1.2.1
This means that the latest version of Tensorflow is not compatible with your code. Can you tell me which tensorflow version you used?

**Comment by NoemieJaquier** [comment]
Hi! 

The latest version of pymanopt (version 0.2.5) is compatible with scipy 1.4.1, therefore the requirement scipy==1.2.1 can be removed, I will update it. 
However, we did not update yet our code to be fully compatible with tensorflow2. I was using tensorflow 1.14.0. 

Hope this helps!

**Comment by gmmarconi** [comment]
Thanks, I managed to install and run the code correctly without the scipy requirement.
